apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-api
spec:
  host: {{ .Values.routes.api }}
  to:
    kind: Service
    name: {{ .Release.Name }}-api
  port:
    targetPort: {{ .Values.api.port }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
